/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadisystem.view;

import cadisystem.model.DAO.UsuarioDAO;
import cadisystem.model.DAO.UsuarioPrivilegioDAO;
import cadisystem.model.dto.usuario.Privilegio;
import cadisystem.model.dto.usuario.Usuario;
import cadisystem.model.dto.usuario.UsuarioPrivilegio;
import cadisystem.model.implement.UsuarioImp;
import cadisystem.model.implement.UsuarioPrivilegioImp;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class ActualizaPrivilegios extends javax.swing.JDialog {

    public List<UsuarioPrivilegio> listado;

    CrearUsuario cu = new CrearUsuario(null, true);

    public UsuarioPrivilegio objUserProv;

    /**
     * Creates new form ActualizaPrivilegios
     */
    public ActualizaPrivilegios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.cargarJCheckBox();
    }

    public JCheckBox getjCheckBox10() {
        return jCheckBox10;
    }

    public void setjCheckBox10(JCheckBox jCheckBox10) {
        this.jCheckBox10 = jCheckBox10;
    }

    public JCheckBox getjCheckBox12() {
        return jCheckBox12;
    }

    public void setjCheckBox12(JCheckBox jCheckBox12) {
        this.jCheckBox12 = jCheckBox12;
    }

    public JCheckBox getjCheckBox14() {
        return jCheckBox14;
    }

    public void setjCheckBox14(JCheckBox jCheckBox14) {
        this.jCheckBox14 = jCheckBox14;
    }

    public JCheckBox getjCheckBox15() {
        return jCheckBox15;
    }

    public void setjCheckBox15(JCheckBox jCheckBox15) {
        this.jCheckBox15 = jCheckBox15;
    }

    public JCheckBox getjCheckBox5() {
        return jCheckBox5;
    }

    public void setjCheckBox5(JCheckBox jCheckBox5) {
        this.jCheckBox5 = jCheckBox5;
    }

    public JCheckBox getjCheckBox6() {
        return jCheckBox6;
    }

    public void setjCheckBox6(JCheckBox jCheckBox6) {
        this.jCheckBox6 = jCheckBox6;
    }

    public JCheckBox getjCheckBox7() {
        return jCheckBox7;
    }

    public void setjCheckBox7(JCheckBox jCheckBox7) {
        this.jCheckBox7 = jCheckBox7;
    }

    public JCheckBox getjCheckBox8() {
        return jCheckBox8;
    }

    public void setjCheckBox8(JCheckBox jCheckBox8) {
        this.jCheckBox8 = jCheckBox8;
    }

    public JCheckBox getjCheckBox9() {
        return jCheckBox9;
    }

    public void setjCheckBox9(JCheckBox jCheckBox9) {
        this.jCheckBox9 = jCheckBox9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        btnGuadrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-cadif1.jpg"))); // NOI18N
        jLabel1.setText("                     Actualizar Privilegios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 876, -1));

        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 136, 94, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 133, 150, -1));

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 132, -1, -1));

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, -1));

        jCheckBox2.setText("jCheckBox1");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 227, 170, -1));

        jCheckBox3.setText("jCheckBox1");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 170, -1));

        btnGuadrar.setText("Guardar");
        btnGuadrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuadrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuadrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 454, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 454, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 454, -1, -1));

        jCheckBox12.setText("Cambiar contraseña");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 200, -1));

        jCheckBox9.setText("Cambiar contraseña");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 210, -1));

        jCheckBox11.setText("Cambiar contraseña");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 210, -1));

        jCheckBox15.setText("Cambiar contraseña");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 220, -1));

        jCheckBox4.setText("Cambiar contraseña");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 210, -1));

        jCheckBox10.setText("Cambiar contraseña");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 190, -1));

        jCheckBox6.setText("Cambiar contraseña");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 180, -1));

        jCheckBox5.setText("Cambiar contraseña");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 180, -1));

        jCheckBox7.setText("Cambiar contraseña");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 260, -1));

        jCheckBox8.setText("Cambiar contraseña");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 180, -1));

        jCheckBox13.setText("Cambiar contraseña");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 220, -1));

        jCheckBox14.setText("Cambiar contraseña");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
     
        if(txtUsuario.getText().equals("")){
                                    String msj = "Debe introducir un nombre de usuario";
                        JOptionPane.showMessageDialog(null, msj, "Error", JOptionPane.ERROR_MESSAGE);
                       
        }
        else{
               Usuario usr;

        usr = this.buscarUsuario();
            if(usr.getId() != -1){
                        listado = this.buscarPrivilegiosDadoUsuario(usr.getId());

        this.getjCheckBox1().setText(listado.get(0).getNombrePrivilegio());
        this.getjCheckBox2().setText(listado.get(1).getNombrePrivilegio());
        this.getjCheckBox3().setText(listado.get(2).getNombrePrivilegio());
        this.getjCheckBox4().setText(listado.get(3).getNombrePrivilegio());
        this.getjCheckBox5().setText(listado.get(4).getNombrePrivilegio());
        this.getjCheckBox6().setText(listado.get(5).getNombrePrivilegio());
        this.getjCheckBox7().setText(listado.get(6).getNombrePrivilegio());
        this.getjCheckBox8().setText(listado.get(7).getNombrePrivilegio());
        this.getjCheckBox9().setText(listado.get(8).getNombrePrivilegio());
        this.getjCheckBox10().setText(listado.get(9).getNombrePrivilegio());
        this.getjCheckBox11().setText(listado.get(10).getNombrePrivilegio());
        this.getjCheckBox12().setText(listado.get(11).getNombrePrivilegio());
        this.getjCheckBox13().setText(listado.get(12).getNombrePrivilegio());
        this.getjCheckBox14().setText(listado.get(13).getNombrePrivilegio());
        this.getjCheckBox15().setText(listado.get(14).getNombrePrivilegio());

        this.seleccionado(this.getjCheckBox1(), listado.get(0).getStatus());
        this.seleccionado(this.getjCheckBox2(), listado.get(1).getStatus());
        this.seleccionado(this.getjCheckBox3(), listado.get(2).getStatus());
        this.seleccionado(this.getjCheckBox4(), listado.get(3).getStatus());
        this.seleccionado(this.getjCheckBox5(), listado.get(4).getStatus());
        this.seleccionado(this.getjCheckBox6(), listado.get(5).getStatus());
        this.seleccionado(this.getjCheckBox7(), listado.get(6).getStatus());
        this.seleccionado(this.getjCheckBox8(), listado.get(7).getStatus());
        this.seleccionado(this.getjCheckBox9(), listado.get(8).getStatus());
        this.seleccionado(this.getjCheckBox10(), listado.get(9).getStatus());
        this.seleccionado(this.getjCheckBox11(), listado.get(10).getStatus());
        this.seleccionado(this.getjCheckBox12(), listado.get(11).getStatus());
        this.seleccionado(this.getjCheckBox13(), listado.get(12).getStatus());
        this.seleccionado(this.getjCheckBox14(), listado.get(13).getStatus());
        this.seleccionado(this.getjCheckBox15(), listado.get(14).getStatus());

        this.getjCheckBox1().setVisible(true);
        this.getjCheckBox2().setVisible(true);
        this.getjCheckBox3().setVisible(true);
        this.getjCheckBox4().setVisible(true);
        this.getjCheckBox5().setVisible(true);
        this.getjCheckBox6().setVisible(true);
        this.getjCheckBox7().setVisible(true);
        this.getjCheckBox8().setVisible(true);
        this.getjCheckBox9().setVisible(true);
        this.getjCheckBox10().setVisible(true);
        this.getjCheckBox11().setVisible(true);
        this.getjCheckBox12().setVisible(true);
        this.getjCheckBox13().setVisible(true);
        this.getjCheckBox14().setVisible(true);
        this.getjCheckBox15().setVisible(true);
            }
            else{
                     String msj = "Usuario no encontrado";
                        JOptionPane.showMessageDialog(null, msj, "Error", JOptionPane.ERROR_MESSAGE);
                       
            }
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox1.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox1.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }

            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox1.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox2.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox2.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox2.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox3.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox3.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }

            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox3.getText())) {
                System.out.println("Eliminado de la lista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    public JCheckBox getjCheckBox11() {
        return jCheckBox11;
    }

    public void setjCheckBox11(JCheckBox jCheckBox11) {
        this.jCheckBox11 = jCheckBox11;
    }

    public JCheckBox getjCheckBox13() {
        return jCheckBox13;
    }

    public void setjCheckBox13(JCheckBox jCheckBox13) {
        this.jCheckBox13 = jCheckBox13;
    }

    public JCheckBox getjCheckBox4() {
        return jCheckBox4;
    }

    public void setjCheckBox4(JCheckBox jCheckBox4) {
        this.jCheckBox4 = jCheckBox4;
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtUsuario.setText("");
        this.getjCheckBox1().setVisible(false);
        this.getjCheckBox2().setVisible(false);
        this.getjCheckBox3().setVisible(false);
        this.getjCheckBox4().setVisible(false);
        this.getjCheckBox5().setVisible(false);
        this.getjCheckBox15().setVisible(false);
        this.getjCheckBox6().setVisible(false);
        this.getjCheckBox7().setVisible(false);
        this.getjCheckBox8().setVisible(false);
        this.getjCheckBox9().setVisible(false);
        this.getjCheckBox10().setVisible(false);
        this.getjCheckBox11().setVisible(false);
        this.getjCheckBox12().setVisible(false);
        this.getjCheckBox13().setVisible(false);
        this.getjCheckBox14().setVisible(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuadrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuadrarActionPerformed

        UsuarioPrivilegioDAO usrdao = new UsuarioPrivilegioImp();
        Integer idUusuarioPriv = listado.get(0).getIdUsuario();
        Integer contador = 0;
        for (int i = 0; i < listado.size(); i++) {

            try {

                usrdao.actualizarEstatusPrivilegios(listado.get(i).getId(), listado.get(i).getStatus());
                System.out.println(listado.get(i).getStatus());
                contador++;
            } catch (Exception ex) {
                Logger.getLogger(ActualizaPrivilegios.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        if (contador.equals(listado.size())) {

            String msj = "Ha cambiado los privilegios satisfactoriamente";
            JOptionPane.showMessageDialog(null, msj, "Información", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();

        }


    }//GEN-LAST:event_btnGuadrarActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox12.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox12.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox12.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox9.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox9.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox9.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox11.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox11.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox11.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox15.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox15.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox15.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox4.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox4.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox4.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox10.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox10.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox10.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox6.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox6.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox6.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox5.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox5.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox5.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox7.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox7.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox7.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox8.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox8.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox8.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox13.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox13.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox13.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        Privilegio priv = new Privilegio();
        Boolean valor = null;

        if (jCheckBox14.isSelected()) {

            for (int i = 0; i < listado.size(); i++) {

                if (jCheckBox14.getText().equals(listado.get(i).getNombrePrivilegio())) {
                    listado.get(i).setStatus("A");
                    valor = true;
                } else {
                    valor = false;
                }

            }
            if (valor) {
                System.out.println("cambiado a A el estatus");
            } else {
                System.out.println("no ha cambiado a A el estatus");

            }

        } else {

            if (this.eliminarCheckBox(jCheckBox14.getText())) {
                System.out.println("Eliminado de la ista temporal");
            } else {

                System.out.println("no encontre el valor en la lista temporal");
            }

        }
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizaPrivilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizaPrivilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizaPrivilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizaPrivilegios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActualizaPrivilegios dialog = new ActualizaPrivilegios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuadrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getjCheckBox1() {
        return jCheckBox1;
    }

    public JCheckBox getjCheckBox2() {
        return jCheckBox2;
    }

    public JCheckBox getjCheckBox3() {
        return jCheckBox3;
    }

    public void cargarJCheckBox() {

        this.getjCheckBox1().setVisible(false);
        this.getjCheckBox2().setVisible(false);
        this.getjCheckBox3().setVisible(false);
        this.getjCheckBox4().setVisible(false);
        this.getjCheckBox5().setVisible(false);
        this.getjCheckBox15().setVisible(false);
        this.getjCheckBox6().setVisible(false);
        this.getjCheckBox7().setVisible(false);
        this.getjCheckBox8().setVisible(false);
        this.getjCheckBox9().setVisible(false);
        this.getjCheckBox10().setVisible(false);
        this.getjCheckBox11().setVisible(false);
        this.getjCheckBox12().setVisible(false);
        this.getjCheckBox13().setVisible(false);
        this.getjCheckBox14().setVisible(false);

    }

    public Usuario buscarUsuario() {
        UsuarioDAO userDAO = new UsuarioImp();
        Usuario user;

        try {
            user = userDAO.buscar(String.valueOf(this.txtUsuario.getText()));

        } catch (Exception ex) {
            user = null;
        }
        return user;
    }

    public List<UsuarioPrivilegio> buscarPrivilegiosDadoUsuario(Integer usuario) {
        List<UsuarioPrivilegio> lista = new ArrayList();
        UsuarioPrivilegioDAO usrp = new UsuarioPrivilegioImp();
        try {
            lista = usrp.buscarPrivilegiosDadoUsuario(usuario);
        } catch (Exception ex) {
            Logger.getLogger(ActualizaPrivilegios.class.getName()).log(Level.SEVERE, null, ex);
        }

        return lista;
    }

    public void seleccionado(javax.swing.JCheckBox jCheckBox, String status) {

        if (status.equals("A")) {

            jCheckBox.setSelected(true);

        } else {

            jCheckBox.setSelected(false);

        }

    }

    public Boolean eliminarCheckBox(String desc) {
        Boolean valor = null;
        for (int i = 0; i < listado.size(); i++) {

            if (desc.equals(listado.get(i).getNombrePrivilegio())) {
                listado.get(i).setStatus("E");
                valor = true;
            } else {
                valor = false;
            }

        }

        return valor;
    }

}
