/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadisystem.view;

import cadisystem.dto.asesor.Asesor;
import cadisystem.dto.curso.Curso;
import cadisystem.dto.seccion.Seccion;
import cadisystem.dto.seccion.SeccionMovimiento;
import cadisystem.dto.seccion.SeccionHistorico;
import cadisystem.model.DAO.AsesorCursoDAO;
import cadisystem.model.DAO.SeccionDAO;
import cadisystem.model.DAO.SeccionMovimientoDAO;
import cadisystem.model.DAO.SeccionHistoricoDAO;
import cadisystem.model.implement.AsesorCursoImp;
import cadisystem.model.implement.SeccionMovimientoImp;
import cadisystem.model.implement.SeccionHistoricoImp;
import cadisystem.model.implement.SeccionImp;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.commons.beanutils.converters.SqlDateConverter;

/**
 *
 * @author carlos
 */
public class AgregarSeccion extends javax.swing.JDialog {

    Boolean filtrarCombo = false;
    Date hoy, inicio;
    ListadoCursos listCurso = null;
    Curso cursoSelected = new Curso();

    public AgregarSeccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cmbAsesor.setVisible(false);
        this.cargarCombos();
        lblSeccionValue.setText(String.valueOf(ObtenerUltimoIdMasUno()));
        Date now = new Date(System.currentTimeMillis());
        SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
        this.lblFechaRegistroValue.setText(String.valueOf(date.format(now)));
        hoy = now;
        //  fechaTentInicio.setMinSelectableDate(hoy);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSeccionValue = new javax.swing.JLabel();
        lblFechaRegistro = new javax.swing.JLabel();
        lblFechaRegistroValue = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        lblEstatusValue = new javax.swing.JLabel();
        btnPlanificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblFechaInicio = new javax.swing.JLabel();
        btnCatalogoCursos = new javax.swing.JButton();
        cursoValue = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmbAsesor = new javax.swing.JComboBox();
        lblAsesor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        fechaTentInicio = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-cadif1.jpg"))); // NOI18N
        jLabel2.setText("  Sección");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblCurso.setText("Curso:");
        getContentPane().add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));

        jLabel1.setText("Sección número:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 129, -1, -1));

        lblSeccionValue.setText("Sección número:");
        getContentPane().add(lblSeccionValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        lblFechaRegistro.setText("Fecha de Registro:");
        getContentPane().add(lblFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 146, -1, -1));

        lblFechaRegistroValue.setText("Sección número:");
        getContentPane().add(lblFechaRegistroValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        lblEstatus.setText("Estado:");
        getContentPane().add(lblEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        lblEstatusValue.setText("Planificada");
        getContentPane().add(lblEstatusValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        btnPlanificar.setText("Planificar");
        btnPlanificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlanificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        lblFechaInicio.setText("Fecha Tentativa de Inicio:");
        getContentPane().add(lblFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        btnCatalogoCursos.setLabel("Ver catálogo");
        btnCatalogoCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCatalogoCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 136, -1));
        getContentPane().add(cursoValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 190, 20));

        cmbAsesor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 200, 50));

        lblAsesor.setText("Asesor:");
        getContentPane().add(lblAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fechaTentInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fechaTentInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 210, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlanificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanificarActionPerformed
        String msj;
        getFechaTentativaInicio();
        Asesor ase = (Asesor) cmbAsesor.getSelectedItem();
        if (compararDosFechas() == null) {
            msj = "Debe seleccionar una fecha Tentativa de Inicio ";
            JOptionPane.showMessageDialog(null, msj, "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!compararDosFechas()) {
            msj = "Seleccione una fecha mayor o igual a la de hoy ";
            JOptionPane.showMessageDialog(null, msj, "Error", JOptionPane.ERROR_MESSAGE);
        }        else if ("".equals(cursoValue.getText())) {
                    msj = "Seleccione un curso del catálogo";
                    JOptionPane.showMessageDialog(null, msj, "Error", JOptionPane.ERROR_MESSAGE);
              } 
        else if (ase.getId() == -1) {
            msj = "Seleccione un asesor";
            JOptionPane.showMessageDialog(null, msj, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            SeccionDAO seccdao = new SeccionImp();
            Seccion seccion = new Seccion();
            seccion.getCurso().setId(cursoSelected.getId());
            seccion.setFechaRegistro(hoy);
            seccion.setFechaTentativaInicio(inicio);
            seccion.getAsesor().setId(ase.getId());
            seccion.getEstado().setId(1);

            try {
                // Inserta los datos de la seccion
                seccdao.insertar(seccion);
                msj = "Ha creado la sección satisfactoriamente";
                // id de la seccion que acabo de registrar
                Integer id = seccdao.obtenerUltimoIdSeccion();
                SeccionMovimiento seccEst = new SeccionMovimiento("Planificada","", hoy,id);
                SeccionMovimientoDAO seccEstImp = new SeccionMovimientoImp();
                seccEstImp.insertar(seccEst);
//  METODO PARA LOS MOVIMIENTOS DE SECCION
//                SeccionHistoricoDAO seccHdao = new SeccionHistoricoImp();
//                String desc = "la sección fué creada el " + lblFechaRegistroValue.getText();
//                SeccionHistorico seccH = new SeccionHistorico(desc, id);
//                seccHdao.insertar(seccH);
                JOptionPane.showMessageDialog(null, msj, "Información", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(AgregarSeccion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnPlanificarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        cmbAsesor.setSelectedIndex(0);
        fechaTentInicio.setDateFormatString("");
              cmbAsesor.setVisible(false);
              cursoValue.setText("");

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCatalogoCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoCursosActionPerformed
        listCurso = new ListadoCursos(null, true);
        listCurso.getBtnGenerarReporte().setVisible(false);
        listCurso.getBtnGenerarReporte().setName("Seleccionar");
        listCurso.setVisible(true);

    }//GEN-LAST:event_btnCatalogoCursosActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        cursoSelected = listCurso.getCursoSeleccionado();
        if (cursoSelected != null) {
            cursoValue.setText(cursoSelected.getNombre());
            System.out.println(cursoSelected.getNombre());
        }
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        cursoSelected = listCurso.getCursoSeleccionado();
        if (cursoSelected != null) {
            
            
            cursoValue.setText(cursoSelected.getNombre());
            SeccionDAO seccdao = new SeccionImp();
            try {
                seccdao.cargarComboAsesorDadiIdCurso(cmbAsesor,cursoSelected.getId());
            } catch (Exception ex) {
                Logger.getLogger(AgregarSeccion.class.getName()).log(Level.SEVERE, null, ex);
            }
            
             cmbAsesor.setVisible(true);
        }
    }//GEN-LAST:event_formWindowGainedFocus
    public Integer ObtenerUltimoIdMasUno() {
        Integer id = -2;
        SeccionDAO secciondao = new SeccionImp();
        try {
            id = secciondao.obtenerUltimoIdSeccion();
        } catch (Exception ex) {
            Logger.getLogger(AgregarSeccion.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id + 1;
    }

    public void cargarCombos() {

        SeccionDAO seccdao = new SeccionImp();
//        try {
//            seccdao.cargarComboCurso(cmbCurso);
//        } catch (Exception ex) {
//            Logger.getLogger(AgregarSeccion.class.getName()).log(Level.SEVERE, null, ex);
//        }

        try {
            seccdao.cargarComboAsesor(cmbAsesor);
        } catch (Exception ex) {
            Logger.getLogger(AgregarSeccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarSeccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarSeccion dialog = new AgregarSeccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public Date getFechaTentativaInicio() {
        Date date;
        Date sqlDate = null;
        if (fechaTentInicio.getDate() == null) {

        } else {
            date = new Date(fechaTentInicio.getDate().getTime());
            if (date == null) {

            } else {

                sqlDate = new Date(date.getTime());
                System.out.println(sqlDate);
                inicio = sqlDate;
            }
        }

        return sqlDate;
    }

    public Boolean compararDosFechas() {
        if (inicio != null) {
            if (inicio.before(hoy)) {
                return false;

            } else {
                return true;
            }
        } else {
            return null;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCatalogoCursos;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPlanificar;
    private javax.swing.JComboBox cmbAsesor;
    private javax.swing.JLabel cursoValue;
    private com.toedter.calendar.JDateChooser fechaTentInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAsesor;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JLabel lblEstatusValue;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFechaRegistro;
    private javax.swing.JLabel lblFechaRegistroValue;
    private javax.swing.JLabel lblSeccionValue;
    // End of variables declaration//GEN-END:variables
}
