/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cadisystem.view;

import cadisystem.model.BD.Conexion;
import cadisystem.model.DAO.UsuarioDAO;
import cadisystem.model.dto.usuario.Usuario;
import cadisystem.model.implement.UsuarioImp;
import java.sql.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author carlos
 */
public class ListadoUsuarios extends javax.swing.JDialog {
      
         Vector<Usuario> listAux,LUsuario;
         Conexion conex = new Conexion();
         Integer cantUsuarios = 0;
         
    public ListadoUsuarios(java.awt.Frame parent, boolean modal) throws Exception{
        super(parent, modal);

        initComponents();
        limpiarTabla();
      
        cargarLista();
        cargarTabla(LUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableUsuario = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        cmbBusqueda = new javax.swing.JComboBox();
        txtBusqueda = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        btnRestablecer = new javax.swing.JButton();
        btnGenreport = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        valueTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-cadif1.jpg"))); // NOI18N
        jLabel1.setText("                   Listado de Usuarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jtableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha de Registro", "Nombre de Usuario", "Correo", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableUsuario);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cmbBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fecha de Registro", "Nombre de Usuario", "Correo", "Estatus" }));

        lblBuscar.setText("Buscar por:");

        btnRestablecer.setText("Restablecer");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });

        btnGenreport.setText("Generar Reporte");
        btnGenreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenreportActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Total:");

        valueTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valueTotal.setText("xyz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGenreport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestablecer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir)
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valueTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuscar)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(valueTotal))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenreport)
                    .addComponent(btnRestablecer)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            UsuarioDAO userDAO = new UsuarioImp();
            Vector<Usuario> listUs = userDAO.listar();
      
            
            if(cmbBusqueda.getSelectedItem().equals("Fecha de Registro")){  
                
                this.busquedaPorFecha(listUs,listAux);
            
            }
            else if(cmbBusqueda.getSelectedItem().equals("Nombre de Usuario")){
                
                 this.busquedaPorUsuario(listUs,listAux);
                
            }
            else if(cmbBusqueda.getSelectedItem().equals("Correo")){
                
                this.busquedaPorCorreo(listUs, listAux);
            }
            else if(cmbBusqueda.getSelectedItem().equals("Estatus")){
                
                this.busquedaPorEstatus(listUs,listAux);
            }
            
            
        } catch (Exception ex) {
            Logger.getLogger(ListadoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
       txtBusqueda.setText("");
       LUsuario.clear();
             try {
                 this.cargarLista();
             } catch (Exception ex) {
                 Logger.getLogger(ListadoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
             }
       this.cargarTabla(LUsuario);
       cmbBusqueda.setSelectedIndex(0);

    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void btnGenreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenreportActionPerformed
       
        JasperReport jr = null;
        String archivo = "C:\\Users\\carlos\\Documents\\NetBeansProjects\\Librerias\\cadisystem\\src\\cadisystem\\report\\ReporteUsuarios.jasper";
               
            Map params = new HashMap<String, String>();
            params.put("saludo","Hola");
          //  params.put("usuarios",listAux);
             JRDataSource jrdt = new JRBeanCollectionDataSource(listAux);
            try {
                jr = (JasperReport) JRLoader.loadObjectFromFile(archivo);
            } catch (JRException ex) {
                Logger.getLogger(ListadoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            JasperPrint jp = null;
            try {
                jp = JasperFillManager.fillReport(jr,params,jrdt);
            } catch (JRException ex) {
                Logger.getLogger(ListadoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            JasperViewer jv = new JasperViewer(jp,false);
           // this.setModal(false);
           this.dispose();
            jv.setVisible(true);
            
            jv.setTitle("Reporte de usuarios");
        
    }//GEN-LAST:event_btnGenreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListadoUsuarios dialog = null;
                try {
                    dialog = new ListadoUsuarios(new javax.swing.JFrame(), true);
                } catch (Exception ex) {
                    Logger.getLogger(ListadoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenreport;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableUsuario;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JLabel valueTotal;
    // End of variables declaration//GEN-END:variables

public void limpiarTabla(){
    
    jtableUsuario.removeAll();
    
}

public void cargarTabla(List<Usuario> LUsuario){
cantUsuarios = 0;
    this.limpiarTabla();
       DefaultTableModel m=(DefaultTableModel)jtableUsuario.getModel();  
    m.setNumRows(0);
            
            for(int i=0;i < LUsuario.size();i++){
                 Vector fila = new Vector();
                fila.add(LUsuario.get(i).getFechaRegistroString());
                fila.add(LUsuario.get(i).getUsername());
                fila.add(LUsuario.get(i).getCorreo());
                fila.add(LUsuario.get(i).getEstatusString());
                cantUsuarios++;
                m.addRow(fila);
            }
            valueTotal.setText(String.valueOf(cantUsuarios));
            
            
  
}

  public void busquedaPorFecha(Vector<Usuario> listUs,Vector<Usuario> listAux){
                listAux.clear();
             String date = String.valueOf(txtBusqueda.getText());
                
               for(int i=0; i < listUs.size();i++){
                   
                   if(date.equals(listUs.get(i).getFechaRegistro()) ||
                      listUs.get(i).getFechaRegistroString().contains(date)){
                       listAux.add(listUs.get(i));
                   }
                   
               }
                    System.out.println("selecciono la fecha");
                    this.cargarTabla(listAux);
      
      
  }
  
   public void busquedaPorUsuario(Vector<Usuario> listUs, Vector<Usuario> listAux){
         listAux.clear();
          String username = String.valueOf(txtBusqueda.getText());
                
               for(int i=0; i < listUs.size();i++){
                   
                   if(username.equals(listUs.get(i).getUsername()) ||
                     listUs.get(i).getUsername().contains(username)){
                       listAux.add(listUs.get(i));
                   }
                   
               }
                    System.out.println("selecciono el usuario");
                    this.cargarTabla(listAux);
      
      
   }
       
   public void busquedaPorCorreo(Vector<Usuario> listUs, Vector<Usuario> listAux){
         listAux.clear();
                String correo = String.valueOf(txtBusqueda.getText());
                
               for(int i=0; i < listUs.size();i++){
                   
                   if(correo.equals(listUs.get(i).getCorreo()) ||
                     listUs.get(i).getCorreo().contains(correo)){
                       listAux.add(listUs.get(i));
                   }
                   
               }
                    System.out.println("selecciono el correo");
                    this.cargarTabla(listAux);
       
       
   } 
   
      public void busquedaPorEstatus(Vector<Usuario> listUs, Vector<Usuario> listAux){
         listAux.clear();
                String estatus = String.valueOf(txtBusqueda.getText());
                
               for(int i=0; i < listUs.size();i++){
                   
                   if(estatus.equals(listUs.get(i).getEstatus()) ||
                     listUs.get(i).getEstatus().contains(estatus)){
                       listAux.add(listUs.get(i));
                   }
                   
               }
                    System.out.println("selecciono el estatus");
                    this.cargarTabla(listAux);
       
       
   }   
   public void cargarLista() throws Exception{
        
        UsuarioDAO userDAO = new UsuarioImp();
         this.listAux = userDAO.listar();
        LUsuario = listAux;
      
   }
}
