/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadisystem.view;

import cadisystem.model.DAO.EstudianteDAO;
import cadisystem.model.dto.estudiante.Estudiante;
import cadisystem.model.implement.EstudianteImp;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author carlos
 */
public class ListadoEstudiantes extends javax.swing.JDialog {

    Vector<Estudiante> LEstudiante;
    Vector<Estudiante> listAux = new Vector<>();
    Integer cantEstudiantes = 0;
  

    public ListadoEstudiantes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        limpiarTabla();
        valueTotal.setText(String.valueOf(cantEstudiantes));
        EstudianteDAO estdao = new EstudianteImp();
        try {
            LEstudiante = estdao.listar();
            listAux = LEstudiante; 
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.cargarTabla(LEstudiante);
        valueTotal.setText(String.valueOf(cantEstudiantes));
    }

    public void limpiarTabla() {

        jtableEstudiante.removeAll();
        

    }

    public void cargarTabla(List<Estudiante> LEstudiante) {
        cantEstudiantes  = 0;    
        this.limpiarTabla();
        DefaultTableModel m = (DefaultTableModel) jtableEstudiante.getModel();
        m.setNumRows(0);

        for (int i = 0; i < LEstudiante.size(); i++) {
            Vector fila = new Vector();
            fila.add(LEstudiante.get(i).getCedula());
            fila.add(LEstudiante.get(i).getNombre());
            fila.add(LEstudiante.get(i).getApellido());
            fila.add(LEstudiante.get(i).getTelefono());
            fila.add(LEstudiante.get(i).getOtroTelefono());
            fila.add(LEstudiante.get(i).getDireccion());
            fila.add(LEstudiante.get(i).getFechaRegistroOut());
            fila.add(LEstudiante.get(i).getSexoString());
            cantEstudiantes++;
            m.addRow(fila);
        }
        
        valueTotal.setText(String.valueOf(cantEstudiantes));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFiltrarPor = new javax.swing.JLabel();
        cmbFiltro = new javax.swing.JComboBox();
        lblBusqueda = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableEstudiante = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        valueTotal = new javax.swing.JLabel();
        btnRestablecer1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-cadif1.jpg"))); // NOI18N
        jLabel1.setText("                   Listado de Estudiantes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblFiltrarPor.setText("Filtrar por:");
        getContentPane().add(lblFiltrarPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 127, 63, -1));

        cmbFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cédula", "Nombre", "Apellido", "Teléfono", "Otro Teléfono", "Dirección", "Fecha de registro", "Sexo" }));
        getContentPane().add(cmbFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 124, 205, -1));

        lblBusqueda.setText("Busqueda:");
        getContentPane().add(lblBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 127, -1, -1));
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 124, 211, -1));

        jtableEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Telefono", "Otro teléfono", "Dirección", "Fecha de Registro", "Sexo"
            }
        ));
        jScrollPane2.setViewportView(jtableEstudiante);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 152, 906, 230));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 123, -1, -1));

        btnGenerarReporte.setText("Generar Reporte");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 130, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotal.setText("Total:");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 50, -1));

        valueTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        valueTotal.setText("xyz");
        getContentPane().add(valueTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 390, 90, -1));

        btnRestablecer1.setText("Restablecer");
        btnRestablecer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecer1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRestablecer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
//        EstudianteDAO estdao = new EstudianteImp();
//        try {
//            LEstudiante = estdao.listar();
//            listAux = LEstudiante; 
//        } catch (Exception ex) {
//            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
//        }
        if (cmbFiltro.getSelectedItem().equals("Cédula")) {
            this.busquedaPorCedula(this.LEstudiante, this.listAux);

        } else if (cmbFiltro.getSelectedItem().equals("Nombre")) {
            this.busquedaPorNombre(LEstudiante, listAux);

        } else if (cmbFiltro.getSelectedItem().equals("Apellido")) {
            this.busquedaPorApellido(LEstudiante, listAux);

        } else if (cmbFiltro.getSelectedItem().equals("Teléfono")) {
            this.busquedaPorTelefono(LEstudiante, listAux);

        } else if (cmbFiltro.getSelectedItem().equals("Otro Teléfono")) {
            this.busquedaPorOtroTelefono(LEstudiante, listAux);

        } else if (cmbFiltro.getSelectedItem().equals("Dirección")) {
            this.busquedaPorDireccion(LEstudiante, listAux);

        } else if (cmbFiltro.getSelectedItem().equals("Fecha de registro")) {
            this.busquedaPorFecha(LEstudiante, listAux);

        } else if (cmbFiltro.getSelectedItem().equals("Sexo")) {
            this.busquedaPorSexo(LEstudiante, listAux);

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
    
        JasperReport jr = null;
        String archivo = "C:\\Users\\carlos\\Documents\\NetBeansProjects\\Librerias\\cadisystem\\src\\cadisystem\\report\\ReporteEstudiantes.jasper";
               
            Map params = new HashMap<String, String>();
          
          //  params.put("usuarios",listAux);
             JRDataSource jrdt = new JRBeanCollectionDataSource(listAux);
            try {
                jr = (JasperReport) JRLoader.loadObjectFromFile(archivo);
            } catch (JRException ex) {
                Logger.getLogger(ListadoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            JasperPrint jp = null;
            try {
                jp = JasperFillManager.fillReport(jr,params,jrdt);
            } catch (JRException ex) {
                Logger.getLogger(ListadoUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
            JasperViewer jv = new JasperViewer(jp,false);
            this.setModal(false);
           this.dispose();
            jv.setVisible(true);
            
            jv.setTitle("Reporte de Estudiantes");
         
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    private void btnRestablecer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecer1ActionPerformed
      jtableEstudiante.removeAll();
      cmbFiltro.setSelectedIndex(0);
      txtBusqueda.setText("");
       EstudianteDAO estdao = new EstudianteImp();
        try {
            LEstudiante = estdao.listar();
            listAux = LEstudiante; 
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.cargarTabla(LEstudiante);
    }//GEN-LAST:event_btnRestablecer1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListadoEstudiantes dialog = new ListadoEstudiantes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnRestablecer1;
    private javax.swing.JComboBox cmbFiltro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jtableEstudiante;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblFiltrarPor;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JLabel valueTotal;
    // End of variables declaration//GEN-END:variables

    public void busquedaPorSexo(Vector<Estudiante> listEs, Vector<Estudiante> listAux) {
       EstudianteDAO estdao = new EstudianteImp();
        this.listAux.removeAllElements();
                try {
                listEs = estdao.listar();
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String busqueda = String.valueOf(txtBusqueda.getText());

        for (int i = 0; i < listEs.size(); i++) {

            if (busqueda.equals(listEs.get(i).getSexoString())
                    || listEs.get(i).getSexoString().contains(busqueda)) {
                listAux.add(listEs.get(i));
            }

        }
        this.cargarTabla(listAux);

    }

    public void busquedaPorDireccion(Vector<Estudiante> listEs, Vector<Estudiante> listAux) {
       EstudianteDAO estdao = new EstudianteImp();
        this.listAux.removeAllElements();
                try {
                listEs = estdao.listar();
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String busqueda = String.valueOf(txtBusqueda.getText());

        for (int i = 0; i < listEs.size(); i++) {

            if (busqueda.equals(listEs.get(i).getDireccion())
                    || listEs.get(i).getDireccion().contains(busqueda)) {
                listAux.add(listEs.get(i));
            }

        }

        this.cargarTabla(listAux);

    }

    public void busquedaPorOtroTelefono(Vector<Estudiante> listEs, Vector<Estudiante> listAux) {
       EstudianteDAO estdao = new EstudianteImp();
        this.listAux.removeAllElements();
                try {
                listEs = estdao.listar();
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String busqueda = String.valueOf(txtBusqueda.getText());

        for (int i = 0; i < listEs.size(); i++) {

            if (busqueda.equals(listEs.get(i).getOtroTelefono())
                    || listEs.get(i).getOtroTelefono().contains(busqueda)) {
                listAux.add(listEs.get(i));
            }

        }
        System.out.println("selecciono el otro telefono");
        this.cargarTabla(listAux);

    }

    public void busquedaPorTelefono(Vector<Estudiante> listEs, Vector<Estudiante> listAux) {
       EstudianteDAO estdao = new EstudianteImp();
        this.listAux.removeAllElements();
                try {
                listEs = estdao.listar();
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String busqueda = String.valueOf(txtBusqueda.getText());

        for (int i = 0; i < listEs.size(); i++) {

            if (busqueda.equals(listEs.get(i).getTelefono())
                    || listEs.get(i).getTelefono().contains(busqueda)) {
                listAux.add(listEs.get(i));
            }

        }
        System.out.println("selecciono el telefono");
        this.cargarTabla(listAux);

    }

    public void busquedaPorApellido(Vector<Estudiante> listEs, Vector<Estudiante> listAux) {
        EstudianteDAO estdao = new EstudianteImp();
        this.listAux.removeAllElements();
                try {
                listEs = estdao.listar();
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String busqueda = String.valueOf(txtBusqueda.getText());

        for (int i = 0; i < listEs.size(); i++) {

            if (busqueda.equals(listEs.get(i).getApellido())
                    || listEs.get(i).getApellido().contains(busqueda)) {
                listAux.add(listEs.get(i));
            }

        }
        System.out.println("selecciono el apellido");
        this.cargarTabla(listAux);

    }

    public void busquedaPorNombre(Vector<Estudiante> listEs, Vector<Estudiante> listAux) {
       EstudianteDAO estdao = new EstudianteImp();
        this.listAux.removeAllElements();
                try {
                listEs = estdao.listar();
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String nombre = String.valueOf(txtBusqueda.getText());

        for (int i = 0; i < listEs.size(); i++) {

            if (nombre.equals(listEs.get(i).getNombre())
                    || listEs.get(i).getNombre().contains(nombre)) {
                listAux.add(listEs.get(i));
            }

        }
        System.out.println("selecciono el nombre");
        this.cargarTabla(listAux);

    }

    public void busquedaPorCedula(Vector<Estudiante> listEs, Vector<Estudiante> listAux) {
         EstudianteDAO estdao = new EstudianteImp();
        this.listAux.removeAllElements();
                try {
                listEs = estdao.listar();
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String cedula = String.valueOf(txtBusqueda.getText());

        for (int i = 0; i < listEs.size(); i++) {

            if (cedula.equals(listEs.get(i).getCedula())
                    || listEs.get(i).getCedula().contains(cedula)) {
                this.listAux.add(listEs.get(i));
            }

        }
        System.out.println("selecciono la cedula");
        this.cargarTabla(listAux);

    }

    public void busquedaPorFecha(Vector<Estudiante> listEs, Vector<Estudiante> listAux) {
            EstudianteDAO estdao = new EstudianteImp();
        this.listAux.removeAllElements();
                try {
                listEs = estdao.listar();
        } catch (Exception ex) {
            Logger.getLogger(ListadoEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        String date = String.valueOf(txtBusqueda.getText());

        for (int i = 0; i < listEs.size(); i++) {

            if (date.equals(listEs.get(i).getFechaRegistroOut())
                    || listEs.get(i).getFechaRegistroOut().contains(date)) {
                listAux.add(listEs.get(i));
            }

        }
       // System.out.println("selecciono la fecha");
        this.cargarTabla(listAux);

    }
}
