/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadisystem.view;

import cadisystem.model.dto.usuario.UsuarioPrivilegio;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author carlos
 */
public class Principal extends javax.swing.JDialog {


 
    public Principal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         inicializarMenuFalse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menugestionar = new javax.swing.JMenu();
        menuusuario = new javax.swing.JMenu();
        menuCrearUsuario = new javax.swing.JMenuItem();
        menuCambiarPrivilegios = new javax.swing.JMenuItem();
        menuListadoUsuario = new javax.swing.JMenuItem();
        menuestudiante = new javax.swing.JMenu();
        menuNuevoEstudiante = new javax.swing.JMenuItem();
        menuListadoEstudiante = new javax.swing.JMenuItem();
        menuAsesor = new javax.swing.JMenu();
        menuNuevoAsesor = new javax.swing.JMenuItem();
        menuAsignarCursos = new javax.swing.JMenuItem();
        menuQuitarCurso = new javax.swing.JMenuItem();
        menuListadoAsesor = new javax.swing.JMenuItem();
        menuCurso = new javax.swing.JMenu();
        menuNuevoCurso = new javax.swing.JMenuItem();
        menuListadoCurso = new javax.swing.JMenuItem();
        menuSeccion = new javax.swing.JMenu();
        menuCrearSeccion = new javax.swing.JMenuItem();
        menuListadoSeccion = new javax.swing.JMenuItem();
        menuVer = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenuItem();
        menuPlanificacion = new javax.swing.JMenu();
        menuInscribirEstudiante = new javax.swing.JMenuItem();
        menuSoporte = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenuItem();
        menuAcerca = new javax.swing.JMenuItem();
        menuPaneldeControl = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/footer.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 264, 1010, 240));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadif1-decimo-aniversario.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 72, 325, 187));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Bienvenido a CADI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("SYSTEM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 100, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 270));

        menugestionar.setText("Gestionar");

        menuusuario.setText("Usuarios");
        menuusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuusuarioActionPerformed(evt);
            }
        });

        menuCrearUsuario.setText("Nuevo");
        menuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearUsuarioActionPerformed(evt);
            }
        });
        menuusuario.add(menuCrearUsuario);

        menuCambiarPrivilegios.setText("Cambiar privilegios");
        menuCambiarPrivilegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCambiarPrivilegiosActionPerformed(evt);
            }
        });
        menuusuario.add(menuCambiarPrivilegios);

        menuListadoUsuario.setText("Listado");
        menuListadoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListadoUsuarioActionPerformed(evt);
            }
        });
        menuusuario.add(menuListadoUsuario);

        menugestionar.add(menuusuario);

        menuestudiante.setText("Estudiante");
        menuestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuestudianteActionPerformed(evt);
            }
        });

        menuNuevoEstudiante.setText("Nuevo");
        menuNuevoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoEstudianteActionPerformed(evt);
            }
        });
        menuestudiante.add(menuNuevoEstudiante);

        menuListadoEstudiante.setText("Listado");
        menuListadoEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListadoEstudianteActionPerformed(evt);
            }
        });
        menuestudiante.add(menuListadoEstudiante);

        menugestionar.add(menuestudiante);

        menuAsesor.setText("Asesor");

        menuNuevoAsesor.setText("Nuevo");
        menuNuevoAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoAsesorActionPerformed(evt);
            }
        });
        menuAsesor.add(menuNuevoAsesor);

        menuAsignarCursos.setText("Asignar cursos");
        menuAsignarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAsignarCursosActionPerformed(evt);
            }
        });
        menuAsesor.add(menuAsignarCursos);

        menuQuitarCurso.setText("Quitar cursos");
        menuQuitarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuitarCursoActionPerformed(evt);
            }
        });
        menuAsesor.add(menuQuitarCurso);

        menuListadoAsesor.setText("Listado");
        menuListadoAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListadoAsesorActionPerformed(evt);
            }
        });
        menuAsesor.add(menuListadoAsesor);

        menugestionar.add(menuAsesor);

        menuCurso.setText("Curso");
        menuCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCursoActionPerformed(evt);
            }
        });

        menuNuevoCurso.setText("Nuevo");
        menuNuevoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoCursoActionPerformed(evt);
            }
        });
        menuCurso.add(menuNuevoCurso);

        menuListadoCurso.setText("Listado");
        menuListadoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListadoCursoActionPerformed(evt);
            }
        });
        menuCurso.add(menuListadoCurso);

        menugestionar.add(menuCurso);

        menuSeccion.setText("Sección");

        menuCrearSeccion.setText("Crear");
        menuCrearSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearSeccionActionPerformed(evt);
            }
        });
        menuSeccion.add(menuCrearSeccion);

        menuListadoSeccion.setText("Listado");
        menuListadoSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListadoSeccionActionPerformed(evt);
            }
        });
        menuSeccion.add(menuListadoSeccion);

        menugestionar.add(menuSeccion);

        jMenuBar1.add(menugestionar);

        menuVer.setText("Ver");
        menuVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerActionPerformed(evt);
            }
        });

        menuVentas.setText("Ventas");
        menuVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVentasActionPerformed(evt);
            }
        });
        menuVer.add(menuVentas);

        jMenuBar1.add(menuVer);

        menuPlanificacion.setText("Transacción");
        menuPlanificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPlanificacionActionPerformed(evt);
            }
        });

        menuInscribirEstudiante.setText("Inscribir estudiante");
        menuInscribirEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInscribirEstudianteActionPerformed(evt);
            }
        });
        menuPlanificacion.add(menuInscribirEstudiante);

        jMenuBar1.add(menuPlanificacion);

        menuSoporte.setText("Soporte");

        menuAyuda.setText("Ayuda");
        menuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAyudaActionPerformed(evt);
            }
        });
        menuSoporte.add(menuAyuda);

        menuAcerca.setText("Acerca del software");
        menuAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcercaActionPerformed(evt);
            }
        });
        menuSoporte.add(menuAcerca);

        jMenuBar1.add(menuSoporte);

        menuPaneldeControl.setText("Panel de control");
        menuPaneldeControl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPaneldeControlMouseClicked(evt);
            }
        });
        menuPaneldeControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPaneldeControlActionPerformed(evt);
            }
        });

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuPaneldeControl.add(menuSalir);

        jMenuBar1.add(menuPaneldeControl);
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNuevoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoEstudianteActionPerformed
        AgregarEstudiante objAgregarEstudiante = new AgregarEstudiante(null, true);
        objAgregarEstudiante.setVisible(true);
    }//GEN-LAST:event_menuNuevoEstudianteActionPerformed

    private void menuListadoEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListadoEstudianteActionPerformed

        ListadoEstudiantes listadoEstudiantes = new ListadoEstudiantes(null, true);
        listadoEstudiantes.setVisible(true);

    }//GEN-LAST:event_menuListadoEstudianteActionPerformed

    private void menuNuevoAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoAsesorActionPerformed
        AgregarAsesor objAgreAsesor = null;
        try {
            objAgreAsesor = new AgregarAsesor(null, true);
        } catch (NoSuchMethodException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        objAgreAsesor.setVisible(true);

    }//GEN-LAST:event_menuNuevoAsesorActionPerformed

    private void menuListadoAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListadoAsesorActionPerformed
        ListadoAsesores objListAses = new ListadoAsesores(null, true);
        objListAses.setVisible(true);
    }//GEN-LAST:event_menuListadoAsesorActionPerformed

    private void menuNuevoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoCursoActionPerformed
        AgregarCurso agregarCurso = new AgregarCurso(null, true);
        agregarCurso.setVisible(true);

    }//GEN-LAST:event_menuNuevoCursoActionPerformed

    private void menuListadoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListadoCursoActionPerformed

        ListadoCursos listCurso = new ListadoCursos(null, true);
        listCurso.setVisible(true);
    }//GEN-LAST:event_menuListadoCursoActionPerformed

    private void menuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAyudaActionPerformed
       Ayuda ayuda = new Ayuda(null,true);
       ayuda.setVisible(true);
    }//GEN-LAST:event_menuAyudaActionPerformed

    private void menuAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcercaActionPerformed
       AcercaSoftware acerS = new AcercaSoftware(null,true);
       acerS.setVisible(true);
    }//GEN-LAST:event_menuAcercaActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuInscribirEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInscribirEstudianteActionPerformed
       InscribirEstudiante inscrEst = new InscribirEstudiante(null,true);
       inscrEst.setVisible(true);


    }//GEN-LAST:event_menuInscribirEstudianteActionPerformed

    private void menuCrearSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearSeccionActionPerformed
        AgregarSeccion agresecc = new AgregarSeccion(null, true);
        agresecc.setVisible(true);
    }//GEN-LAST:event_menuCrearSeccionActionPerformed

    private void menuListadoSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListadoSeccionActionPerformed
        ListadoSecciones listadoSecciones = new ListadoSecciones(null, true);
        listadoSecciones.setVisible(true);
    }//GEN-LAST:event_menuListadoSeccionActionPerformed

    private void menuestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuestudianteActionPerformed


    }//GEN-LAST:event_menuestudianteActionPerformed

    private void menuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearUsuarioActionPerformed
        CrearUsuario crearUsuario = new CrearUsuario(null, true);
        crearUsuario.setVisible(true);
    }//GEN-LAST:event_menuCrearUsuarioActionPerformed

    private void menuListadoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListadoUsuarioActionPerformed
        try {
            ListadoUsuarios listado = null;

            listado = new ListadoUsuarios(null, true);
            listado.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuListadoUsuarioActionPerformed

    private void menuusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuusuarioActionPerformed

    private void menuPaneldeControlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPaneldeControlMouseClicked

    }//GEN-LAST:event_menuPaneldeControlMouseClicked

    private void menuPaneldeControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPaneldeControlActionPerformed

        CambiarContraseña cambiarContraseña = new CambiarContraseña(null, true);
        cambiarContraseña.setVisible(true);
    }//GEN-LAST:event_menuPaneldeControlActionPerformed

    private void menuCambiarPrivilegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCambiarPrivilegiosActionPerformed

        ActualizaPrivilegios actPriv = new ActualizaPrivilegios(null, true);
        actPriv.setVisible(true);

    }//GEN-LAST:event_menuCambiarPrivilegiosActionPerformed

    private void menuCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCursoActionPerformed

    }//GEN-LAST:event_menuCursoActionPerformed

    private void menuAsignarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAsignarCursosActionPerformed
        AgregarCursoAsesor asesorc = new AgregarCursoAsesor(null, true);
        asesorc.setVisible(true);
    }//GEN-LAST:event_menuAsignarCursosActionPerformed

    private void menuQuitarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuitarCursoActionPerformed
        QuitarCursosAsesor quitaCurrso = new QuitarCursosAsesor(null, true);
        quitaCurrso.setVisible(true);
    }//GEN-LAST:event_menuQuitarCursoActionPerformed

    private void menuPlanificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPlanificacionActionPerformed
    }//GEN-LAST:event_menuPlanificacionActionPerformed

    private void menuVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVentasActionPerformed
     Ventas ventas = new Ventas(null,true);
     ventas.setVisible(true);
    }//GEN-LAST:event_menuVentasActionPerformed

    private void menuVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerActionPerformed
      
    }//GEN-LAST:event_menuVerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal dialog = new Principal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAcerca;
    private javax.swing.JMenu menuAsesor;
    private javax.swing.JMenuItem menuAsignarCursos;
    private javax.swing.JMenuItem menuAyuda;
    private javax.swing.JMenuItem menuCambiarPrivilegios;
    private javax.swing.JMenuItem menuCrearSeccion;
    private javax.swing.JMenuItem menuCrearUsuario;
    private javax.swing.JMenu menuCurso;
    private javax.swing.JMenuItem menuInscribirEstudiante;
    private javax.swing.JMenuItem menuListadoAsesor;
    private javax.swing.JMenuItem menuListadoCurso;
    private javax.swing.JMenuItem menuListadoEstudiante;
    private javax.swing.JMenuItem menuListadoSeccion;
    private javax.swing.JMenuItem menuListadoUsuario;
    private javax.swing.JMenuItem menuNuevoAsesor;
    private javax.swing.JMenuItem menuNuevoCurso;
    private javax.swing.JMenuItem menuNuevoEstudiante;
    private javax.swing.JMenu menuPaneldeControl;
    private javax.swing.JMenu menuPlanificacion;
    private javax.swing.JMenuItem menuQuitarCurso;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenu menuSeccion;
    private javax.swing.JMenu menuSoporte;
    private javax.swing.JMenuItem menuVentas;
    private javax.swing.JMenu menuVer;
    private javax.swing.JMenu menuestudiante;
    private javax.swing.JMenu menugestionar;
    private javax.swing.JMenu menuusuario;
    // End of variables declaration//GEN-END:variables

    public void cargarMenuSegunPrivilegios(List<UsuarioPrivilegio> usp) {

        for (int i = 0; i < usp.size(); i++) {

            if (usp.get(i).getStatus().equals("A")) {

                if (usp.get(i).getNombrePrivilegio().equals("Agregar, Modificar y Eliminar  Estudiante")) {

                    menugestionar.setVisible(true);
                    menuestudiante.setVisible(true);
                    menuNuevoEstudiante.setVisible(true);

                }

                if (usp.get(i).getNombrePrivilegio().equals("Ver Listado de Estudiantes")) {

                    menugestionar.setVisible(true);
                    menuestudiante.setVisible(true);
                    menuListadoEstudiante.setVisible(true);

                }

                if (usp.get(i).getNombrePrivilegio().equals("Ver Ventas")) {

                    menuVer.setVisible(true);
                    menuVentas.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Cambiar privilegios")) {

                    menugestionar.setVisible(true);
                    menuCambiarPrivilegios.setVisible(true);
                    menuusuario.setVisible(true);
                    

                }
                 if (usp.get(i).getNombrePrivilegio().equals("Agregar Usuarios")) {

                    menugestionar.setVisible(true);
                    menuCrearUsuario.setVisible(true);
                    menuusuario.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Ver Listado de Usuarios")) {

                    menugestionar.setVisible(true);
                    menuListadoUsuario.setVisible(true);
                    menuusuario.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Agregar, Modificar y Eliminar Asesor")) {

                    menugestionar.setVisible(true);
                    menuNuevoAsesor.setVisible(true);
                    menuAsesor.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Ver Listado de Asesores")) {

                    menugestionar.setVisible(true);
                    menuListadoAsesor.setVisible(true);
                    menuAsesor.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Agregar Curso a Asesores")) {

                    menugestionar.setVisible(true);
                    menuAsignarCursos.setVisible(true);
                    menuAsesor.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Quitar Cursos a Asesores")) {

                    menuQuitarCurso.setVisible(true);
                    menuAsesor.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Agregar Curso")) {

                    menuNuevoCurso.setVisible(true);
                    menuCurso.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Ver Listado de Cursos")) {

                    menuListadoCurso.setVisible(true);
                    menuAsesor.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Planificar Sección")) {

                    menugestionar.setVisible(true);
                    menuCrearSeccion.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Ver Listado de Secciones")) {

                    menugestionar.setVisible(true);
                    menuListadoSeccion.setVisible(true);

                }
                if (usp.get(i).getNombrePrivilegio().equals("Inscribir Estudiante")) {

                    menuPlanificacion.setVisible(true);
                    menuInscribirEstudiante.setVisible(true);

                }
            }

        }

    }

    private void inicializarMenuFalse() {

        menuCambiarPrivilegios.setVisible(false);
        menuCrearSeccion.setVisible(false);
        menuCrearUsuario.setVisible(false);
        menuInscribirEstudiante.setVisible(false);
        menuListadoAsesor.setVisible(false);
        menuListadoCurso.setVisible(false);
        menuListadoEstudiante.setVisible(false);
        menuListadoSeccion.setVisible(false);
        menuListadoUsuario.setVisible(false);
        menuNuevoAsesor.setVisible(false);
        menuNuevoCurso.setVisible(false);
        menuNuevoEstudiante.setVisible(false);
        menuPlanificacion.setVisible(false);
        menuVentas.setVisible(false);
        menuVer.setVisible(false);
        menugestionar.setVisible(false);
        menuusuario.setVisible(false);
        menuAsesor.setVisible(false);
        menuCurso.setVisible(false);
        menuAsignarCursos.setVisible(false);
        menuQuitarCurso.setVisible(false);
        

    }
}
