/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadisystem.view;

import cadisystem.dto.asesor.Asesor;
import cadisystem.dto.asesor.AsesorCurso;
import cadisystem.dto.curso.Curso;
import cadisystem.herramientas.Tools;
import cadisystem.model.DAO.AsesorCursoDAO;
import cadisystem.model.DAO.AsesorDAO;
import cadisystem.model.DAO.CursoDAO;
import cadisystem.model.implement.AsesorCursoImp;
import cadisystem.model.implement.AsesorImp;
import cadisystem.model.implement.CursoImp;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlos
 */
public class QuitarCursosAsesor extends javax.swing.JDialog {

    Tools tools = new Tools();
    Asesor asesor = new Asesor();
    Vector<AsesorCurso> LAsesorCursos = new Vector();
    Vector<AsesorCurso> LAsesorCursoEliminar = new Vector();

    public QuitarCursosAsesor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cmbCurso.removeAllItems();
        cmbCurso.setVisible(false);
        btnAgrCurso.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblBusqueda = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgrCurso = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtableCurso = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblAsesor = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-cadif1.jpg"))); // NOI18N
        jLabel1.setText("    Eliminar cursos al Asesor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        lblBusqueda.setText("Cédula del Asesor:");
        getContentPane().add(lblBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 20));

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 211, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        btnAgrCurso.setText("Quitar curso");
        btnAgrCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrCursoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgrCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 120, -1));

        jtableCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cursos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtableCurso);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 420, 230));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 80, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 90, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 90, -1));
        getContentPane().add(lblAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 152, 270, 30));

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped

        tools.validarSoloNumeros(evt);

    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (txtBusqueda.getText().equals("")) {
            String msj = "Introduzca la cédula del asesor";
            JOptionPane.showMessageDialog(null, msj, "Error", JOptionPane.ERROR_MESSAGE);
        } else {

            AsesorDAO asesordao = new AsesorImp();
            try {
                asesor = asesordao.buscar(txtBusqueda.getText(), asesor);
                if (asesor.getId() == -1) {

                    String msj = "Asesor no encontrado";
                    JOptionPane.showMessageDialog(null, msj, "Información", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    lblAsesor.setText("" + asesor.getNombre() + " " + asesor.getApellido());
                    cargarComboCursos(asesor.getId(),cmbCurso);
                    btnAgrCurso.setVisible(true);
                    cmbCurso.setVisible(true);
                }

            } catch (Exception ex) {
                Logger.getLogger(AgregarCursoAsesor.class.getName()).log(Level.SEVERE, null, ex);
            }

            AsesorCursoDAO asec = new AsesorCursoImp();
            try {
                LAsesorCursos = asec.listadoCursosDaoIdAsesor(asesor.getId());
                cargarTabla(LAsesorCursos);
            } catch (Exception ex) {
                Logger.getLogger(AgregarCursoAsesor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgrCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrCursoActionPerformed
        Curso curso = (Curso) cmbCurso.getSelectedItem();
        AsesorCurso asec = new AsesorCurso();
        asec.setIdCurso(curso.getId());
        asec.setCurso(curso.getNombre());
        asec.setIdAsesor(asesor.getId());
        if (curso.getNombre().equals("Seleccione")) {
            String msj = "Seleccione un curso";
            JOptionPane.showMessageDialog(null, msj, "Error", JOptionPane.ERROR_MESSAGE);
        } else {
  //          LAsesorCursos.add(asec);
            LAsesorCursoEliminar.add(asec);
            eliminarItemSeleccionadoDeLista(asec);

            cargarTabla(LAsesorCursos);
            cmbCurso.removeItem(curso);
            cmbCurso.setSelectedIndex(0);
            btnGuardar.setVisible(true);

        }
    }//GEN-LAST:event_btnAgrCursoActionPerformed
    public void eliminarItemSeleccionadoDeLista(AsesorCurso asec){
       
        Vector<AsesorCurso> listAux = new Vector();
        
       for(AsesorCurso ase : LAsesorCursos){
           if(!ase.getIdCurso().equals(asec.getIdCurso())){
               listAux.add(ase);
          
           }
       }
       LAsesorCursos = new Vector();
       LAsesorCursos = listAux;

    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (LAsesorCursoEliminar.isEmpty()) {
            String msj = "Seleccione al menos un curso a Eliminar";
            JOptionPane.showMessageDialog(null, msj, "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            AsesorCursoDAO asecdao = new AsesorCursoImp();
            Integer contador = 0;

            for (AsesorCurso asec : LAsesorCursoEliminar) {
                try {
                    asec.setIdAsesorCurso(asecdao.obtenerIDAsesorCursoParaEliminar(asesor.getId(),asec.getIdCurso()));
                } catch (Exception ex) {
                    Logger.getLogger(QuitarCursosAsesor.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    asecdao.eliminar(asec);
                    contador++;

                } catch (Exception ex) {
                    Logger.getLogger(AgregarCursoAsesor.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            if (contador == LAsesorCursoEliminar.size()) {
                String msj = "Han desasociado los cursos al asesor " + asesor.getNombre() + " " + asesor.getApellido();
                JOptionPane.showMessageDialog(null, msj, "Información", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtBusqueda.setText("");
        lblAsesor.setText("");
        jtableCurso.removeAll();
        cmbCurso.setSelectedIndex(0);
        btnAgrCurso.setVisible(false);
        cmbCurso.setVisible(false);
        LAsesorCursos.clear();
        LAsesorCursoEliminar.clear();
         jtableCurso.removeAll();
        
    }//GEN-LAST:event_btnLimpiarActionPerformed
    public Vector<AsesorCurso> obtenerListCursoDadoIdAsesor(Integer idAsesor) {
        Vector<AsesorCurso> LAsec = null;
        AsesorCurso asec = new AsesorCurso();
        AsesorCursoDAO asecdao = new AsesorCursoImp();
        try {

            LAsec = asecdao.listadoCursosDaoIdAsesor(idAsesor);

        } catch (Exception ex) {
            Logger.getLogger(QuitarCursosAsesor.class.getName()).log(Level.SEVERE, null, ex);
        }
        return LAsec;
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        String msj = "¿Está seguro(a) de cancelar la eliminación de cursos?";
        if (JOptionPane.showConfirmDialog(null, msj, "Error", JOptionPane.ERROR_MESSAGE) == 0) {

            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed
    public void cargarComboCursos(Integer idAsesor, JComboBox cmb) {
            AsesorCursoDAO asecdao = new AsesorCursoImp();
        try {
            asecdao.cargarComboCursoDadoIdAsesor(idAsesor,cmb);
        } catch (Exception ex) {
            Logger.getLogger(QuitarCursosAsesor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuitarCursosAsesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuitarCursosAsesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuitarCursosAsesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuitarCursosAsesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuitarCursosAsesor dialog = new QuitarCursosAsesor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrCurso;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox cmbCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtableCurso;
    private javax.swing.JLabel lblAsesor;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

    public void cargarTabla(Vector<AsesorCurso> LCurso) {

        if (!LCurso.isEmpty()) {

            jtableCurso.removeAll();
            DefaultTableModel m = (DefaultTableModel) jtableCurso.getModel();
            m.setNumRows(0);

            for (int i = 0; i < LCurso.size(); i++) {
                Vector fila = new Vector();
                fila.add(LCurso.get(i).getCurso());
                m.addRow(fila);
            }

        }

    }

    public void cargarCombo() {
        CursoDAO cursodao = new CursoImp();
        try {
            cursodao.cargarComboCurso(this.cmbCurso);
        } catch (Exception ex) {
            Logger.getLogger(AgregarCursoAsesor.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
